#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK_LOG_DIR="$(cd "$ROOT_DIR/../.." && pwd)/work-logs"

LATEST_READINESS_JSON="$WORK_LOG_DIR/latest-ui-release-readiness.json"
LATEST_HANDOFF_MD="$WORK_LOG_DIR/latest-ui-release-handoff.md"
LATEST_ONE_PASS_SH="$WORK_LOG_DIR/latest-ui-release-one-pass.sh"
LATEST_OPERATOR_BRIEF_MD="$WORK_LOG_DIR/latest-ui-release-operator-brief.md"
LATEST_BUNDLE_MANIFEST_JSON="$WORK_LOG_DIR/latest-ui-release-handoff-bundle-manifest.json"
LATEST_SMOKE_GATE_MD="$WORK_LOG_DIR/latest-ui-smoke-release-gate.md"
RELEASE_GATE_SCRIPT="$ROOT_DIR/scripts/run-ui-smoke-release.sh"

fail() {
  echo "[ui-handoff-verify] ERROR: $1" >&2
  exit 1
}

for required in \
  "$LATEST_READINESS_JSON" \
  "$LATEST_HANDOFF_MD" \
  "$LATEST_ONE_PASS_SH" \
  "$LATEST_OPERATOR_BRIEF_MD" \
  "$LATEST_BUNDLE_MANIFEST_JSON" \
  "$RELEASE_GATE_SCRIPT"
do
  [[ -f "$required" ]] || fail "Missing required artifact: $required"
done

[[ -x "$LATEST_ONE_PASS_SH" ]] || fail "One-pass script is not executable: $LATEST_ONE_PASS_SH"

grep -q 'npm run release:ui-gate' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing final release:ui-gate command"
grep -q 'REQUIRED_ONE_PASS_METADATA_VARS=(' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing required one-pass metadata list"
grep -q 'Invalid one-pass pre-gate metadata format' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing invalid-metadata format guard"
grep -q 'Verified one-pass pre-gate metadata is present and well-formed before release gate execution.' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing successful metadata format validation marker"
grep -Fq '[[ "$GATE_RUN_TOKEN" =~ ^one-pass-[0-9]{10}-[0-9]+$ ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing run-token metadata format validation"
grep -Fq '[[ "$EXPECTED_COMMIT_SHA" =~ ^[a-f0-9]{7,40}$ ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing commit metadata format validation"
grep -Fq '[[ "$EXPECTED_BRANCH_NAME" =~ ^[A-Za-z0-9._/-]+$ ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing branch metadata format validation"
grep -Fq '[[ "$EXPECTED_READINESS_TIMESTAMP" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}([+-][0-9]{4}|Z)$ ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing readiness-timestamp metadata format validation"
grep -Fq '[[ "$EXPECTED_READINESS_STATUS" =~ ^(READY|NOT_READY)$ ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing readiness-status metadata format validation"
grep -Fq '[[ "$EXPECTED_BLOCKING_CHECKS" =~ ^[0-9]+$ ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing readiness blocking-check metadata format validation"
grep -Fq '[[ "$EXPECTED_READINESS_SHA256" =~ ^[a-f0-9]{64}$ ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing readiness SHA-256 metadata format validation"
grep -Fq '[[ "$EXPECTED_READINESS_REPORT_JSON_SHA256" =~ ^[a-f0-9]{64}$ ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing readiness report JSON SHA-256 metadata format validation"
grep -Fq '[[ "$EXPECTED_READINESS_REPORT_MD_SHA256" =~ ^[a-f0-9]{64}$ ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing readiness report markdown SHA-256 metadata format validation"
grep -Fq '[[ "$EXPECTED_BUNDLE_MANIFEST_SHA256" =~ ^[a-f0-9]{64}$ ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing handoff bundle manifest SHA-256 metadata format validation"
grep -Fq '[[ "$EXPECTED_BUNDLE_MANIFEST_PATH" == "work-logs/latest-ui-release-handoff-bundle-manifest.json" ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing handoff bundle manifest path metadata validation"
grep -q 'EXPECTED_BUNDLE_MANIFEST_ABS_PATH="$MANIFEST_ROOT/$EXPECTED_BUNDLE_MANIFEST_PATH"' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing stable handoff bundle manifest absolute-path resolution"
grep -Fq '[[ -f "$EXPECTED_BUNDLE_MANIFEST_ABS_PATH" ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing stable handoff bundle manifest file-existence assertion"
grep -q 'CURRENT_BUNDLE_MANIFEST_SHA256=' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing stable handoff bundle manifest on-disk SHA-256 capture"
grep -Fq '[[ "$CURRENT_BUNDLE_MANIFEST_SHA256" == "$EXPECTED_BUNDLE_MANIFEST_SHA256" ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing stable handoff bundle manifest SHA-256 drift assertion"
grep -q 'CURRENT_BUNDLE_MANIFEST_SELF_PATH=' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing stable handoff bundle manifest self-path capture from disk"
grep -Fq '[[ "$CURRENT_BUNDLE_MANIFEST_SELF_PATH" == "$EXPECTED_BUNDLE_MANIFEST_PATH" ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing stable handoff bundle manifest self-path drift assertion"
grep -q 'Verified stable handoff bundle manifest file, SHA-256, and self-path before release gate execution.' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing stable handoff bundle manifest preflight success marker"
grep -Fq '[[ "$EXPECTED_HANDOFF_SHA256" =~ ^[a-f0-9]{64}$ ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing handoff markdown SHA-256 metadata format validation"
grep -Fq '[[ "$EXPECTED_OPERATOR_BRIEF_SHA256" =~ ^[a-f0-9]{64}$ ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing operator brief SHA-256 metadata format validation"
grep -Fq '[[ "$EXPECTED_ONE_PASS_SHA256" =~ ^[a-f0-9]{64}$ ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing one-pass SHA-256 metadata format validation"
grep -Fq '[[ "$EXPECTED_WEB_DIR_PATH" == "$ROOT_DIR" ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing expected web-directory path metadata validation"
grep -q 'Interactive terminal required' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing interactive-terminal guard"
grep -q 'EXPECTED_WEB_DIR_PATH=' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing generated working-directory path capture"
grep -q 'Verified working directory path matches generated web directory before release gate prerequisites.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-prerequisite working-directory path assertion"
grep -q 'Verified current working directory still matches generated web directory before release gate.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate working-directory drift assertion"
grep -q 'Verified PASS evidence: work-logs/latest-ui-smoke-release-gate.md' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing PASS evidence assertion after gate execution"
grep -q 'bash ../work-logs/latest-ui-release-one-pass.sh' "$LATEST_HANDOFF_MD" || fail "Handoff markdown is missing prepared one-pass execution guidance"
grep -q 'Stable latest file: `work-logs/latest-ui-smoke-release-gate.md`' "$LATEST_HANDOFF_MD" || fail "Handoff markdown is missing stable latest smoke-evidence pointer"
grep -q 'LATEST_SMOKE_LOG_FILE=' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing stable latest smoke-log pointer declaration"
grep -q 'sync_latest_smoke_log()' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing stable smoke-log sync helper"
grep -q 'sync_latest_smoke_log' "$RELEASE_GATE_SCRIPT" || fail "Release gate script never syncs the stable latest smoke-log pointer"
grep -q 'Verified smoke evidence mtime epoch format for gate freshness check.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing smoke evidence mtime-epoch format assertion"
grep -q 'Verified smoke evidence freshness for current gate run.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing smoke evidence freshness assertion"
grep -q 'Verified gate run token match in smoke evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing gate run token assertion"
grep -q 'Verified commit hash match in smoke evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing commit hash assertion"
grep -q 'Verified branch match in smoke evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing branch assertion"
grep -q 'Verified final git commit/branch snapshot remains well-formed and matches one-pass pre-gate expectations.' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing final git snapshot consistency success marker"
grep -q 'Verified web directory path remains anchored to one-pass pre-gate expectation during release gate execution.' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing final web-directory path consistency success marker"
grep -q 'Web directory path:' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing final web-directory snapshot output in smoke evidence"
grep -Fq '[[ "$COMMIT_SHA" =~ ^[a-f0-9]{7,40}$ ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing final commit snapshot format validation"
grep -Fq '[[ "$BRANCH_NAME" =~ ^[A-Za-z0-9._/-]+$ ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing final branch snapshot format validation"
grep -Fq '[[ "$COMMIT_SHA" == "$EXPECTED_COMMIT_SHA" ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing final commit snapshot drift assertion"
grep -Fq '[[ "$BRANCH_NAME" == "$EXPECTED_BRANCH_NAME" ]]' "$RELEASE_GATE_SCRIPT" || fail "Release gate script is missing final branch snapshot drift assertion"
grep -q 'Verified readiness timestamp match in smoke evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing readiness-timestamp assertion"
grep -q 'Verified readiness status match in smoke evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing readiness-status assertion"
grep -q 'Verified readiness blocking-check count match in smoke evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing readiness blocking-check assertion"
grep -q 'Verified readiness snapshot SHA-256 match in smoke evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing readiness SHA-256 assertion"
grep -q 'Verified readiness report JSON SHA-256 match in smoke evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing readiness report JSON SHA-256 assertion"
grep -q 'Verified readiness report markdown SHA-256 match in smoke evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing readiness report markdown SHA-256 assertion"
grep -q 'Verified handoff bundle manifest SHA-256 match in smoke evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing handoff bundle manifest SHA-256 assertion"
grep -q 'Verified handoff bundle manifest path match in smoke evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing handoff bundle manifest path assertion"
grep -q 'Verified handoff markdown SHA-256 match in smoke evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing handoff markdown SHA-256 assertion"
grep -q 'Verified operator brief SHA-256 match in smoke evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing operator brief SHA-256 assertion"
grep -q 'RELEASE_GATE_EXPECTED_ONE_PASS_SHA256=' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing one-pass SHA-256 capture before gate execution"
grep -q 'RELEASE_GATE_EXPECTED_WEB_DIR_PATH=' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing expected web-directory path capture before gate execution"
grep -q 'export RELEASE_GATE_RUN_TOKEN .*RELEASE_GATE_EXPECTED_ONE_PASS_SHA256 .*RELEASE_GATE_EXPECTED_WEB_DIR_PATH' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing one-pass SHA-256/web-directory export coverage"
grep -q 'Verified one-pass script SHA-256 match in smoke evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing one-pass script SHA-256 assertion"
grep -q 'Verified web directory path match in smoke evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing web-directory path assertion"
grep -q 'Readiness confirmed READY (0 blockers) before release gate.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate READY readiness assertion"
grep -q 'Verified required pre-gate artifacts exist before metadata capture.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing required pre-gate artifact existence assertion"
grep -q 'Verified release gate start epoch format for pre-gate evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate release gate start epoch format assertion"
grep -q 'Verified deterministic pre-gate metadata capture before release gate.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing deterministic pre-gate metadata capture assertion"
grep -q 'RELEASE_GATE_EXPECTED_BUNDLE_MANIFEST_PATH=' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing stable bundle manifest self-path capture before gate execution"
grep -q 'RELEASE_GATE_EXPECTED_BUNDLE_MANIFEST_PATH' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing stable bundle manifest self-path export/metadata coverage"
grep -q 'Verified commit hash metadata format for pre-gate evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate commit hash metadata format assertion"
grep -q 'Verified branch metadata format for pre-gate evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate branch metadata format assertion"
grep -q 'Verified branch is attached (not detached HEAD) for pre-gate evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate detached-HEAD assertion"
grep -q 'Verified pre-gate git HEAD metadata remains stable before gate execution.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate git HEAD metadata drift assertion"
grep -q 'RESOLVED_GIT_COMMON_DIR=$(cd "$GIT_COMMON_DIR" && pwd -P)' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing resolved git common-dir capture"
grep -q 'RESOLVED_GIT_DIR=$(cd "$GIT_DIR" && pwd -P)' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing resolved git dir capture"
grep -q 'Verified resolved git metadata paths remain stable before gate execution.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing resolved git metadata path drift assertion"
grep -q 'Verified readiness timestamp metadata format for pre-gate evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate readiness timestamp format assertion"
grep -q 'READINESS_TIMESTAMP_AFTER=' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate refreshed readiness timestamp capture"
grep -q 'Verified pre-gate readiness timestamp metadata remains stable before gate execution.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate readiness timestamp drift assertion"
grep -q 'Verified readiness status metadata format for pre-gate evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate readiness status metadata format assertion"
grep -q 'Verified pre-gate readiness status/blocking metadata remains stable before gate execution.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate readiness status/blocking metadata drift assertion"
grep -q 'Verified pre-gate readiness metadata remains READY with zero blockers.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate readiness metadata drift assertion"
grep -q 'Verified release gate run-token format for pre-gate evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate release gate run-token format assertion"
grep -q 'Verified readiness blocking-check metadata format for pre-gate evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate readiness blocking-check metadata format assertion"
grep -q 'Verified SHA-256 metadata format for pre-gate evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate SHA-256 metadata format assertion"
grep -q 'Verified pre-gate handoff bundle manifest SHA-256 remains stable before gate execution.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate handoff bundle manifest SHA-256 drift assertion"
grep -q 'Assert stable handoff bundle manifest self-path remains work-logs/latest-ui-release-handoff-bundle-manifest.json before gate execution' "$LATEST_HANDOFF_MD" || fail "Handoff markdown is missing stable handoff bundle manifest self-path assertion note"
grep -q 'Verified stable handoff bundle manifest self-path before release gate execution.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate handoff bundle manifest self-path assertion"
grep -q 'Verified pre-gate handoff markdown SHA-256 remains stable before gate execution.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate handoff markdown SHA-256 drift assertion"
grep -q 'Verified pre-gate operator brief SHA-256 remains stable before gate execution.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate operator brief SHA-256 drift assertion"
grep -q 'Verified pre-gate one-pass script SHA-256 remains stable before gate execution.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate one-pass script SHA-256 drift assertion"
grep -q 'Assert smoke evidence contains expected web directory path from one-pass pre-gate check' "$LATEST_HANDOFF_MD" || fail "Handoff markdown is missing expected web-directory path note"
grep -q 'Verified readiness refresh epoch format for pre-gate evidence.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate readiness refresh-epoch format assertion"
grep -q 'Verified readiness snapshot freshness for current pre-gate refresh.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate readiness freshness assertion"
grep -q 'Verified readiness report freshness for current pre-gate refresh.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate readiness-report freshness assertion"
grep -q 'Verified pre-gate readiness report mtimes remain stable before gate execution.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate readiness-report mtime drift assertion"
grep -q 'Verified pre-gate readiness report SHA-256 values remain stable before gate execution.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate readiness-report SHA-256 drift assertion"
grep -q 'Verified git repository context exists before release gate.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate git repository-context assertion"
grep -q 'Verified git execution context prefix before release gate.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate git root-prefix assertion"
grep -q 'Verified active git work-tree context before release gate.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate active git work-tree assertion"
grep -q 'Verified git execution context is outside .git metadata directory before release gate.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate git-inside-git-dir assertion"
grep -q 'Verified git common-dir exists before release gate.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate git common-dir assertion"
grep -q 'Verified git dir exists before release gate.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate git-dir assertion"
grep -q 'Assert resolved git common-dir and git-dir paths remain stable before gate execution' "$LATEST_HANDOFF_MD" || fail "Handoff markdown is missing resolved git metadata path drift assertion note"
grep -q 'Git tracked changes clean before release gate.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate git tracked cleanliness assertion"
grep -q 'Git untracked files clean before release gate.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate git untracked cleanliness assertion"
grep -q 'Verified no in-progress git operations before release gate.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate in-progress git-operation assertion"
grep -q 'Verified no git index lock before release gate.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing pre-gate git index-lock assertion"
if grep -q 'npm run deps:playwright-host' "$LATEST_ONE_PASS_SH"; then
  grep -q 'sudo -n true' "$LATEST_ONE_PASS_SH" || fail "One-pass script includes deps:playwright-host but is missing non-interactive sudo pre-auth check (sudo -n true)"
  grep -q 'Verified sudo pre-authenticated for host dependency install.' "$LATEST_ONE_PASS_SH" || fail "One-pass script is missing sudo pre-auth success marker"
fi
grep -q 'Stable latest handoff path' "$LATEST_HANDOFF_MD" || fail "Handoff markdown is missing expected stable-pointer metadata"
grep -q 'One-pass script' "$LATEST_OPERATOR_BRIEF_MD" || fail "Operator brief is missing one-pass script reference"
grep -q 'latest-ui-smoke-release-gate.md' "$LATEST_OPERATOR_BRIEF_MD" || fail "Operator brief is missing stable latest smoke-evidence pointer"
grep -Eq 'Run (the prepared one-pass handoff script|this) in an interactive elevated host terminal' "$LATEST_OPERATOR_BRIEF_MD" || fail "Operator brief is missing interactive one-pass execution guidance"

node -e "const fs=require('fs');const crypto=require('crypto');const manifestPath=process.argv[1];const m=JSON.parse(fs.readFileSync(manifestPath,'utf8'));const artifacts=(m.artifacts||{});const checksummed=['latestReadinessJson','latestReadinessReportJson','latestReadinessReportMarkdown','latestHandoffMarkdown','latestOnePassScript','latestOperatorBrief'];for(const key of checksummed){if(!artifacts[key]||!artifacts[key].path||!artifacts[key].sha256){console.error('[ui-handoff-verify] manifest missing checksummed entry:',key);process.exit(1);}const file=artifacts[key].path;if(!fs.existsSync(file)){console.error('[ui-handoff-verify] manifest file missing on disk:',file);process.exit(1);}const digest=crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');if(digest!==artifacts[key].sha256){console.error('[ui-handoff-verify] manifest checksum mismatch:',key);process.exit(1);}}if(!artifacts.latestBundleManifest||!artifacts.latestBundleManifest.path){console.error('[ui-handoff-verify] manifest missing self-entry path: latestBundleManifest');process.exit(1);}if(artifacts.latestBundleManifest.path!==manifestPath){console.error('[ui-handoff-verify] manifest self-entry path mismatch:',artifacts.latestBundleManifest.path,'!=',manifestPath);process.exit(1);}" "$LATEST_BUNDLE_MANIFEST_JSON" || fail "Bundle manifest hash validation failed"

READINESS_STATUS="$(node -e "const fs=require('fs');const d=JSON.parse(fs.readFileSync(process.argv[1],'utf8'));process.stdout.write(String(d.status||'UNKNOWN'));" "$LATEST_READINESS_JSON")"
BLOCKING_CHECKS="$(node -e "const fs=require('fs');const d=JSON.parse(fs.readFileSync(process.argv[1],'utf8'));process.stdout.write(String(d.blockingChecks ?? 'NA'));" "$LATEST_READINESS_JSON")"

echo "[ui-handoff-verify] PASS"
echo "[ui-handoff-verify] Readiness status: $READINESS_STATUS"
echo "[ui-handoff-verify] Blocking checks : $BLOCKING_CHECKS"
echo "[ui-handoff-verify] Handoff         : $LATEST_HANDOFF_MD"
echo "[ui-handoff-verify] One-pass script : $LATEST_ONE_PASS_SH"
echo "[ui-handoff-verify] Operator brief  : $LATEST_OPERATOR_BRIEF_MD"
echo "[ui-handoff-verify] Bundle manifest : $LATEST_BUNDLE_MANIFEST_JSON"
if [[ -f "$LATEST_SMOKE_GATE_MD" ]]; then
  echo "[ui-handoff-verify] Smoke evidence  : $LATEST_SMOKE_GATE_MD"
else
  echo "[ui-handoff-verify] Smoke evidence  : (not yet generated; expected after interactive release:ui-gate pass/fail run)"
fi
